// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public ByteArray playerUsername;
            [FieldOffset(16)]
            public System.Single playerColorR;
            [FieldOffset(20)]
            public System.Single playerColorG;
            [FieldOffset(24)]
            public System.Single playerColorB;
            [FieldOffset(28)]
            public System.Single playerMetallic;
            [FieldOffset(32)]
            public System.Single playerSmoothness;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerUsernameMask;
            playerUsernameSimulationFrame = frame;
            FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerColorRMask;
            playerColorRSimulationFrame = frame;
            FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerColorGMask;
            playerColorGSimulationFrame = frame;
            FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerColorBMask;
            playerColorBSimulationFrame = frame;
            FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerMetallicMask;
            playerMetallicSimulationFrame = frame;
            FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerSmoothnessMask;
            playerSmoothnessSimulationFrame = frame;
        }

        public static unsafe _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 36) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 36) " +
                    "for component with ID 20");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 20");
            }

            var orig = new _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142();

            var comp = (Interop*)data;

            orig.playerUsername = comp->playerUsername.Data != null ? System.Text.Encoding.UTF8.GetString((byte*)comp->playerUsername.Data, (int)comp->playerUsername.Length) : null;
            orig.playerColorR = comp->playerColorR;
            orig.playerColorG = comp->playerColorG;
            orig.playerColorB = comp->playerColorB;
            orig.playerMetallic = comp->playerMetallic;
            orig.playerSmoothness = comp->playerSmoothness;

            return orig;
        }


        public static uint playerUsernameMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame playerUsernameSimulationFrame;
        public System.String playerUsername;
        public static uint playerColorRMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame playerColorRSimulationFrame;
        public System.Single playerColorR;
        public static uint playerColorGMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame playerColorGSimulationFrame;
        public System.Single playerColorG;
        public static uint playerColorBMask => 0b00000000000000000000000000001000;
        public AbsoluteSimulationFrame playerColorBSimulationFrame;
        public System.Single playerColorB;
        public static uint playerMetallicMask => 0b00000000000000000000000000010000;
        public AbsoluteSimulationFrame playerMetallicSimulationFrame;
        public System.Single playerMetallic;
        public static uint playerSmoothnessMask => 0b00000000000000000000000000100000;
        public AbsoluteSimulationFrame playerSmoothnessSimulationFrame;
        public System.Single playerSmoothness;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 20;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000111111;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 6;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;

        private static readonly float _playerColorR_Min = -9223372036854775808f;
        private static readonly float _playerColorR_Max = 9223372036854775807f;
        private static readonly float _playerColorG_Min = -9223372036854775808f;
        private static readonly float _playerColorG_Max = 9223372036854775807f;
        private static readonly float _playerColorB_Min = -9223372036854775808f;
        private static readonly float _playerColorB_Max = 9223372036854775807f;
        private static readonly float _playerMetallic_Min = -9223372036854775808f;
        private static readonly float _playerMetallic_Max = 9223372036854775807f;
        private static readonly float _playerSmoothness_Min = -9223372036854775808f;
        private static readonly float _playerSmoothness_Max = 9223372036854775807f;

        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.playerUsernameSimulationFrame = other.playerUsernameSimulationFrame;
                this.playerUsername = other.playerUsername;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.playerColorRSimulationFrame = other.playerColorRSimulationFrame;
                this.playerColorR = other.playerColorR;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.playerColorGSimulationFrame = other.playerColorGSimulationFrame;
                this.playerColorG = other.playerColorG;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.playerColorBSimulationFrame = other.playerColorBSimulationFrame;
                this.playerColorB = other.playerColorB;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.playerMetallicSimulationFrame = other.playerMetallicSimulationFrame;
                this.playerMetallic = other.playerMetallic;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.playerSmoothnessSimulationFrame = other.playerSmoothnessSimulationFrame;
                this.playerSmoothness = other.playerSmoothness;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 6);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.playerUsername;
                bitStream.WriteShortString(fieldValue);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.playerColorR, _playerColorR_Min, _playerColorR_Max, "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerColorR", logger);
                var fieldValue = data.playerColorR;
                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.playerColorG, _playerColorG_Min, _playerColorG_Max, "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerColorG", logger);
                var fieldValue = data.playerColorG;
                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.playerColorB, _playerColorB_Min, _playerColorB_Max, "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerColorB", logger);
                var fieldValue = data.playerColorB;
                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.playerMetallic, _playerMetallic_Min, _playerMetallic_Max, "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerMetallic", logger);
                var fieldValue = data.playerMetallic;
                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.playerSmoothness, _playerSmoothness_Min, _playerSmoothness_Max, "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerSmoothness", logger);
                var fieldValue = data.playerSmoothness;
                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;

            return mask;
        }

        public static _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(6);
            }

            var val = new _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142();
            if (bitStream.ReadMask())
            {

                val.playerUsername = bitStream.ReadShortString();
                val.FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerUsernameMask;
            }
            if (bitStream.ReadMask())
            {

                val.playerColorR = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerColorRMask;
            }
            if (bitStream.ReadMask())
            {

                val.playerColorG = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerColorGMask;
            }
            if (bitStream.ReadMask())
            {

                val.playerColorB = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerColorBMask;
            }
            if (bitStream.ReadMask())
            {

                val.playerMetallic = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerMetallicMask;
            }
            if (bitStream.ReadMask())
            {

                val.playerSmoothness = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142.playerSmoothnessMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142(" +
                $" playerUsername: { this.playerUsername }" +
                $" playerColorR: { this.playerColorR }" +
                $" playerColorG: { this.playerColorG }" +
                $" playerColorB: { this.playerColorB }" +
                $" playerMetallic: { this.playerMetallic }" +
                $" playerSmoothness: { this.playerSmoothness }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(6, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(6, '0') })";
        }
    }

}
