// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Entity target;
            [FieldOffset(4)]
            public System.Single trailDuration;
            [FieldOffset(8)]
            public System.Byte enabled;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791.targetMask;
            targetSimulationFrame = frame;
            FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791.trailDurationMask;
            trailDurationSimulationFrame = frame;
            FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791.enabledMask;
            enabledSimulationFrame = frame;
        }

        public static unsafe _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 9) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 9) " +
                    "for component with ID 18");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 18");
            }

            var orig = new _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791();

            var comp = (Interop*)data;

            orig.target = comp->target;
            orig.trailDuration = comp->trailDuration;
            orig.enabled = comp->enabled != 0;

            return orig;
        }


        public static uint targetMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame targetSimulationFrame;
        public Entity target;
        public static uint trailDurationMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame trailDurationSimulationFrame;
        public System.Single trailDuration;
        public static uint enabledMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame enabledSimulationFrame;
        public System.Boolean enabled;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 18;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000111;
        public bool HasFields() => true;
        public bool HasRefFields() => true;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 3;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return new HashSet<Entity>()
            {
                this.target,
            };
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            uint refsMask = 0;

            if (this.target == fromEntity)
            {
                this.target = toEntity;
                refsMask |= 1 << 0;
            }

            FieldsMask |= refsMask;

            return refsMask;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            Entity absoluteEntity;
            IEntityMapper.Error err;
            err = mapper.MapToAbsoluteEntity(this.target, false, out absoluteEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.target = absoluteEntity;
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            Entity relativeEntity;
            IEntityMapper.Error err;
            // We assume that the inConnection held changes with unresolved references, so the 'createMapping=true' is
            // there only because there's a chance that the parent creation change will be processed after this one
            // meaning there's no mapping for the parent yet. This wouldn't be necessary if mapping creation would happen
            // in the clientWorld via create/destroy requests while here we would only check whether mapping exists or not.
            var createParentMapping_target = true;
            err = mapper.MapToRelativeEntity(this.target, createParentMapping_target,
             out relativeEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.target = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;

        private static readonly float _trailDuration_Min = -9223372036854775808f;
        private static readonly float _trailDuration_Max = 9223372036854775807f;

        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.targetSimulationFrame = other.targetSimulationFrame;
                this.target = other.target;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.trailDurationSimulationFrame = other.trailDurationSimulationFrame;
                this.trailDuration = other.trailDuration;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.enabledSimulationFrame = other.enabledSimulationFrame;
                this.enabled = other.enabled;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 3);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.target;
                bitStream.WriteEntity(fieldValue);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.trailDuration, _trailDuration_Min, _trailDuration_Max, "_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791.trailDuration", logger);
                var fieldValue = data.trailDuration;
                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.enabled;
                bitStream.WriteBool(fieldValue);
            }
            mask >>= 1;

            return mask;
        }

        public static _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(3);
            }

            var val = new _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791();
            if (bitStream.ReadMask())
            {

                val.target = bitStream.ReadEntity();
                val.FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791.targetMask;
            }
            if (bitStream.ReadMask())
            {

                val.trailDuration = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791.trailDurationMask;
            }
            if (bitStream.ReadMask())
            {

                val.enabled = bitStream.ReadBool();
                val.FieldsMask |= _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791.enabledMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791(" +
                $" target: { this.target }" +
                $" trailDuration: { this.trailDuration }" +
                $" enabled: { this.enabled }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(3, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(3, '0') })";
        }
    }

}
