// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _60786269438aa4c6c8c3c4f9b60e4b9b_cff3e7b2a1804b3b803b84611d55ad00 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public ByteArray username;
            [FieldOffset(16)]
            public ByteArray message;
        }

        public static unsafe _60786269438aa4c6c8c3c4f9b60e4b9b_cff3e7b2a1804b3b803b84611d55ad00 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 32) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 32) " +
                    "for command with ID 6");
            }

            var orig = new _60786269438aa4c6c8c3c4f9b60e4b9b_cff3e7b2a1804b3b803b84611d55ad00();
            var comp = (Interop*)data;
            orig.username = comp->username.Data != null ? System.Text.Encoding.UTF8.GetString((byte*)comp->username.Data, (int)comp->username.Length) : null;
            orig.message = comp->message.Data != null ? System.Text.Encoding.UTF8.GetString((byte*)comp->message.Data, (int)comp->message.Length) : null;
            return orig;
        }

        public System.String username;
        public System.String message;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Target { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        public uint GetComponentType() => 6;
        public bool UsesMeta { get; set; }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _60786269438aa4c6c8c3c4f9b60e4b9b_cff3e7b2a1804b3b803b84611d55ad00(
            Entity entity,
            System.String username,
            System.String message
        )
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Target = default;
            Routing = MessageTarget.All;
            SenderParticipant = 0;
            SenderClientID = default;
            Frame = 0;
            UsesMeta = false;

            this.username = username; 
            this.message = message; 
        }
        
        public static void Serialize(_60786269438aa4c6c8c3c4f9b60e4b9b_cff3e7b2a1804b3b803b84611d55ad00 commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteShortString(commandData.username);
            bitStream.WriteShortString(commandData.message);
        }
        
        public static _60786269438aa4c6c8c3c4f9b60e4b9b_cff3e7b2a1804b3b803b84611d55ad00 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var datausername = bitStream.ReadShortString();
            var datamessage = bitStream.ReadShortString();
    
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_cff3e7b2a1804b3b803b84611d55ad00()
            {
                Entity = entity,
                Routing = target,
                Target = target,
                username = datausername,
                message = datamessage
            };   
        }
    }

}
