// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_696ede3cb5824ecfb45f2fd9eeea696e : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_57a6f7063d9447b4844c354b39c7ac73 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_cca014976ec7458bb7cfb569861d06d4 : ReferenceBinding
    {   
        private global::VFX.TargetPosition CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::VFX.TargetPosition)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override Entity Value
        {
            get { return coherenceSync.CoherenceBridge.UnityObjectToEntityId(CastedUnityComponent.target); }
            set { CastedUnityComponent.target = coherenceSync.CoherenceBridge.EntityIdToTransform(value); }
        }

        protected override (Entity value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).target;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).targetSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.target = Value;
            }
            else
            {
                update.target = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.targetSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_40cf0d297d504bb8b5c7cd4e64f51d0e : FloatBinding
    {   
        private global::VFX.TargetPosition CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::VFX.TargetPosition)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.trailDuration); }
            set { CastedUnityComponent.trailDuration = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).trailDuration;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).trailDurationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.trailDuration = Value;
            }
            else
            {
                update.trailDuration = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.trailDurationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_8c71093b534f4150866272b9948e18ae : BoolBinding
    {   
        private global::VFX.TargetPosition CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::VFX.TargetPosition)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).enabled;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_3b4a0bdd583e4e0d928b5d19e000b5a5 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_7736649631221385927);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_7736649631221385927";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_7736649631221385927)coherenceComponent).Speed;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_7736649631221385927)coherenceComponent).SpeedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_7736649631221385927)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Speed = Value;
            }
            else
            {
                update.Speed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SpeedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_7736649631221385927();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_f2f118564fb74d6aaa0385401db6432d : StringBinding
    {   
        private global::NetworkedPlayer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::NetworkedPlayer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.playerUsername); }
            set { CastedUnityComponent.playerUsername = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerUsername;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerUsernameSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.playerUsername = Value;
            }
            else
            {
                update.playerUsername = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.playerUsernameSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_f6a4f53a346242baa4391794d08e2e15 : FloatBinding
    {   
        private global::NetworkedPlayer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::NetworkedPlayer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.playerColorR); }
            set { CastedUnityComponent.playerColorR = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerColorR;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerColorRSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.playerColorR = Value;
            }
            else
            {
                update.playerColorR = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.playerColorRSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_0f7ed0ed47c946dbaee73cc7c78de21f : FloatBinding
    {   
        private global::NetworkedPlayer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::NetworkedPlayer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.playerColorG); }
            set { CastedUnityComponent.playerColorG = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerColorG;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerColorGSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.playerColorG = Value;
            }
            else
            {
                update.playerColorG = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.playerColorGSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_3a6a333c8323450c9ef698115c8eb174 : FloatBinding
    {   
        private global::NetworkedPlayer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::NetworkedPlayer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142";
        public override uint FieldMask => 0b00000000000000000000000000001000;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.playerColorB); }
            set { CastedUnityComponent.playerColorB = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerColorB;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerColorBSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.playerColorB = Value;
            }
            else
            {
                update.playerColorB = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.playerColorBSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_60d282c3692144618204ff603de84e9d : FloatBinding
    {   
        private global::NetworkedPlayer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::NetworkedPlayer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142";
        public override uint FieldMask => 0b00000000000000000000000000010000;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.playerMetallic); }
            set { CastedUnityComponent.playerMetallic = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerMetallic;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerMetallicSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.playerMetallic = Value;
            }
            else
            {
                update.playerMetallic = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.playerMetallicSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_01fa9186742f4bd1a68400847bd3b484 : FloatBinding
    {   
        private global::NetworkedPlayer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::NetworkedPlayer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142";
        public override uint FieldMask => 0b00000000000000000000000000100000;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.playerSmoothness); }
            set { CastedUnityComponent.playerSmoothness = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerSmoothness;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent).playerSmoothnessSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.playerSmoothness = Value;
            }
            else
            {
                update.playerSmoothness = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.playerSmoothnessSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_9064713401945964142();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_60786269438aa4c6c8c3c4f9b60e4b9b : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_60786269438aa4c6c8c3c4f9b60e4b9b>();
        
        private global::NetworkedChat _60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f_CommandTarget;
        private global::NetworkedChat _60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77_CommandTarget;
        private global::NetworkedChat _60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["696ede3cb5824ecfb45f2fd9eeea696e"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_696ede3cb5824ecfb45f2fd9eeea696e(),
			["57a6f7063d9447b4844c354b39c7ac73"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_57a6f7063d9447b4844c354b39c7ac73(),
			["cca014976ec7458bb7cfb569861d06d4"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_cca014976ec7458bb7cfb569861d06d4(),
			["40cf0d297d504bb8b5c7cd4e64f51d0e"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_40cf0d297d504bb8b5c7cd4e64f51d0e(),
			["8c71093b534f4150866272b9948e18ae"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_8c71093b534f4150866272b9948e18ae(),
			["3b4a0bdd583e4e0d928b5d19e000b5a5"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_3b4a0bdd583e4e0d928b5d19e000b5a5(),
			["f2f118564fb74d6aaa0385401db6432d"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_f2f118564fb74d6aaa0385401db6432d(),
			["f6a4f53a346242baa4391794d08e2e15"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_f6a4f53a346242baa4391794d08e2e15(),
			["0f7ed0ed47c946dbaee73cc7c78de21f"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_0f7ed0ed47c946dbaee73cc7c78de21f(),
			["3a6a333c8323450c9ef698115c8eb174"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_3a6a333c8323450c9ef698115c8eb174(),
			["60d282c3692144618204ff603de84e9d"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_60d282c3692144618204ff603de84e9d(),
			["01fa9186742f4bd1a68400847bd3b484"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_01fa9186742f4bd1a68400847bd3b484(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_60786269438aa4c6c8c3c4f9b60e4b9b()
        {
            bakedCommandBindings.Add("214d4bb7b7e54ce08b322137ad61806f", BakeCommandBinding__60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f);
            bakedCommandBindings.Add("6c41276e5edb42cb9643d0d9e417bf77", BakeCommandBinding__60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77);
            bakedCommandBindings.Add("eb6f4128fa8c4a16a35f041a202f4715", BakeCommandBinding__60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f_CommandTarget = (global::NetworkedChat)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"NetworkedChat.ReceiveMessage",
            	"(System.StringSystem.StringSystem.String)",
            	SendCommand__60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f,
            	ReceiveLocalCommand__60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f,
            	MessageTarget.All,
            	_60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.username = (System.String)requestArgs.Args[0];
            command.message = (System.String)requestArgs.Args[1];
            command.styleType = (System.String)requestArgs.Args[2];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.username = (System.String)requestArgs.Args[0];
            command.message = (System.String)requestArgs.Args[1];
            command.styleType = (System.String)requestArgs.Args[2];

            ReceiveCommand__60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f(command);
        }

        private void ReceiveCommand__60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f(_60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f command)
        {
            var target = _60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f_CommandTarget;
			target.ReceiveMessage((System.String)(command.username),(System.String)(command.message),(System.String)(command.styleType));
        }
        private void BakeCommandBinding__60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77_CommandTarget = (global::NetworkedChat)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"NetworkedChat.ReceiveBetAnnouncement",
            	"(System.String)",
            	SendCommand__60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77,
            	ReceiveLocalCommand__60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77,
            	MessageTarget.All,
            	_60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77(GenericCommandRequestArgs requestArgs)
        {
            var command = new _60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.message = (System.String)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77(GenericCommandRequestArgs requestArgs)
        {
            var command = new _60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.message = (System.String)requestArgs.Args[0];

            ReceiveCommand__60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77(command);
        }

        private void ReceiveCommand__60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77(_60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77 command)
        {
            var target = _60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77_CommandTarget;
			target.ReceiveBetAnnouncement((System.String)(command.message));
        }
        private void BakeCommandBinding__60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715_CommandTarget = (global::NetworkedChat)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"NetworkedChat.ReceiveWinAnnouncement",
            	"(System.String)",
            	SendCommand__60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715,
            	ReceiveLocalCommand__60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715,
            	MessageTarget.All,
            	_60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715(GenericCommandRequestArgs requestArgs)
        {
            var command = new _60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.message = (System.String)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715(GenericCommandRequestArgs requestArgs)
        {
            var command = new _60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.message = (System.String)requestArgs.Args[0];

            ReceiveCommand__60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715(command);
        }

        private void ReceiveCommand__60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715(_60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715 command)
        {
            var target = _60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715_CommandTarget;
			target.ReceiveWinAnnouncement((System.String)(command.message));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f castedCommand:
                    ReceiveCommand__60786269438aa4c6c8c3c4f9b60e4b9b_214d4bb7b7e54ce08b322137ad61806f(castedCommand);
                    break;
                case _60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77 castedCommand:
                    ReceiveCommand__60786269438aa4c6c8c3c4f9b60e4b9b_6c41276e5edb42cb9643d0d9e417bf77(castedCommand);
                    break;
                case _60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715 castedCommand:
                    ReceiveCommand__60786269438aa4c6c8c3c4f9b60e4b9b_eb6f4128fa8c4a16a35f041a202f4715(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_60786269438aa4c6c8c3c4f9b60e4b9b Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_60786269438aa4c6c8c3c4f9b60e4b9b>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
