// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_696ede3cb5824ecfb45f2fd9eeea696e : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_57a6f7063d9447b4844c354b39c7ac73 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_cca014976ec7458bb7cfb569861d06d4 : ReferenceBinding
    {   
        private global::VFX.TargetPosition CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::VFX.TargetPosition)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override Entity Value
        {
            get { return coherenceSync.CoherenceBridge.UnityObjectToEntityId(CastedUnityComponent.target); }
            set { CastedUnityComponent.target = coherenceSync.CoherenceBridge.EntityIdToTransform(value); }
        }

        protected override (Entity value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).target;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).targetSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.target = Value;
            }
            else
            {
                update.target = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.targetSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_40cf0d297d504bb8b5c7cd4e64f51d0e : FloatBinding
    {   
        private global::VFX.TargetPosition CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::VFX.TargetPosition)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.trailDuration); }
            set { CastedUnityComponent.trailDuration = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).trailDuration;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).trailDurationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.trailDuration = Value;
            }
            else
            {
                update.trailDuration = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.trailDurationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_60786269438aa4c6c8c3c4f9b60e4b9b_8c71093b534f4150866272b9948e18ae : BoolBinding
    {   
        private global::VFX.TargetPosition CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::VFX.TargetPosition)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791);
        public override string CoherenceComponentName => "_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).enabled;

            var simFrame = ((_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _60786269438aa4c6c8c3c4f9b60e4b9b_3871810461409951791();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_60786269438aa4c6c8c3c4f9b60e4b9b : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_60786269438aa4c6c8c3c4f9b60e4b9b>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["696ede3cb5824ecfb45f2fd9eeea696e"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_696ede3cb5824ecfb45f2fd9eeea696e(),
			["57a6f7063d9447b4844c354b39c7ac73"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_57a6f7063d9447b4844c354b39c7ac73(),
			["cca014976ec7458bb7cfb569861d06d4"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_cca014976ec7458bb7cfb569861d06d4(),
			["40cf0d297d504bb8b5c7cd4e64f51d0e"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_40cf0d297d504bb8b5c7cd4e64f51d0e(),
			["8c71093b534f4150866272b9948e18ae"] = new Binding_60786269438aa4c6c8c3c4f9b60e4b9b_8c71093b534f4150866272b9948e18ae(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_60786269438aa4c6c8c3c4f9b60e4b9b()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_60786269438aa4c6c8c3c4f9b60e4b9b Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_60786269438aa4c6c8c3c4f9b60e4b9b>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
